<?xml version="1.0"?>
<package format="3">
  <name>hazard_guard_sensor_config</name>
  <version>0.1.0</version>
  <description>Shared sensor profiles for HazardGuard ROS 2 packages.</description>
  <maintainer email="gw010101@naver.com">kohs2k21</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <test_depend>ament_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
